// export const ourClients = [
//   { id: 0, img: "/assets/home/sponserLogo.png" },
//   { id: 1, img: "/assets/home/sponserLogo1.png" },
//   { id: 2, img: "/assets/home/sponserLogo2.png" },
//   { id: 3, img: "/assets/home/sponserLogo3.png" },
//   { id: 4, img: "/assets/home/sponserLogo4.jpeg" },
//   { id: 5, img: "/assets/home/sponserLogo5.png" },
//   { id: 6, img: "/assets/home/sponserLogo6.png" },
//   { id: 7, img: "/assets/home/sponserLogo7.png" },
//   { id: 8, img: "/assets/home/sponserLogo8.png" },
//   { id: 9, img: "/assets/home/sponserLogo9.png" },
//   { id: 10, img: "/assets/home/sponserLogo10.png" },
//   { id: 11, img: "/assets/home/sponserLogo11.png" },
//   { id: 12, img: "/assets/home/sponserLogo12.png" },
//   { id: 13, img: "/assets/home/sponserLogo13.png" },
//   { id: 14, img: "/assets/home/sponserLogo14.png" },
//   { id: 15, img: "/assets/home/sponserLogo15.png" },
//   { id: 16, img: "/assets/home/sponserLogo16.png" },
//   { id: 17, img: "/assets/home/sponserLogo17.png" },
//   { id: 18, img: "/assets/home/sponserLogo18.png" },
//   { id: 19, img: "/assets/home/sponserLogo15.png" },
//   { id: 20, img: "/assets/home/sponserLogo10.png" },
//   { id: 21, img: "/assets/home/sponserLogo7.png" },
//   // { id: 22, img: "/assets/home/sponserLogo.png" },
// ];
export const ourClients = [
  { id: 1, img: "/assets/home/kalpataru.jpeg" },
  { id: 2, img: "/assets/home/lodha.jpeg" },
  { id: 3, img: "/assets/home/ho.jpeg" },
  // { id: 0, img: "/assets/home/ho.jpeg" },
  { id: 4, img: "/assets/home/AshieshShah.jpeg" },
  { id: 5, img: "/assets/home/homeland.jpeg" },
  { id: 6, img: "/assets/home/garnet_interiors_logo.jpeg" },
  { id: 7, img: "/assets/home/snn-builders.jpeg" },
  { id: 8, img: "/assets/home/unity-group.jpeg" },
  { id: 9, img: "/assets/home/zz.jpeg" },
  { id: 10, img: "/assets/home/piramal.png" },
  { id: 11, img: "/assets/home/bnk.png" },
  { id: 12, img: "/assets/home/wa-logo-dark.png" },
  { id: 13, img: "/assets/home/trivie.png" },
  { id: 14, img: "/assets/home/vadera.png" },
  { id: 15, img: "/assets/home/narsi.png" },
  { id: 16, img: "/assets/home/padams.png" },
  { id: 17, img: "/assets/home/sumadhura.png" },
  { id: 18, img: "/assets/home/Ensemble.png" },
  { id: 19, img: "/assets/home/My_Home_Group.png" },
  { id: 20, img: "/assets/home/prestige-group.png" },
  { id: 21, img: "/assets/home/K_Raheja_Corp.webp" },
  { id: 22, img: "/assets/home/cauvery.webp" }
];
